-- Expansion seed: ~80 additional entries per industry (safe to re-run)
DO $$
DECLARE
  cid uuid;
  scope text;
  level text;
  scopes text[] := ARRAY['in_industry', 'all'];
  levels text[] := ARRAY['student', 'entry', 'mid', 'senior', 'global'];
  companies jsonb;
  rec jsonb;
BEGIN
  companies := '[
    {"name":"HSBC","domain":"hsbc.com","industry":"Investment Banking"},
    {"name":"BNP Paribas","domain":"bnpparibas.com","industry":"Investment Banking"},
    {"name":"Nomura","domain":"nomura.com","industry":"Investment Banking"},
    {"name":"Macquarie","domain":"macquarie.com","industry":"Investment Banking"},
    {"name":"Société Générale","domain":"societegenerale.com","industry":"Investment Banking"},
    {"name":"Credit Agricole CIB","domain":"ca-cib.com","industry":"Investment Banking"},
    {"name":"Standard Chartered","domain":"sc.com","industry":"Investment Banking"},
    {"name":"Santander","domain":"santander.com","industry":"Investment Banking"},
    {"name":"UniCredit","domain":"unicredit.eu","industry":"Investment Banking"},
    {"name":"ING","domain":"ing.com","industry":"Investment Banking"},
    {"name":"Mediobanca","domain":"mediobanca.com","industry":"Investment Banking"},
    {"name":"Natixis","domain":"natixis.com","industry":"Investment Banking"},
    {"name":"Berenberg","domain":"berenberg.com","industry":"Investment Banking"},
    {"name":"Commerzbank","domain":"commerzbank.com","industry":"Investment Banking"},
    {"name":"ABN AMRO","domain":"abnamro.com","industry":"Investment Banking"},
    {"name":"Nordea","domain":"nordea.com","industry":"Investment Banking"},
    {"name":"SEB","domain":"sebgroup.com","industry":"Investment Banking"},
    {"name":"BMO Capital Markets","domain":"bmo.com","industry":"Investment Banking"},
    {"name":"TD Securities","domain":"td.com","industry":"Investment Banking"},
    {"name":"Scotiabank","domain":"scotiabank.com","industry":"Investment Banking"},
    {"name":"CIBC","domain":"cibc.com","industry":"Investment Banking"},
    {"name":"Mizuho","domain":"mizuhogroup.com","industry":"Investment Banking"},
    {"name":"Daiwa Securities","domain":"daiwa.com","industry":"Investment Banking"},
    {"name":"MUFG","domain":"mufg.jp","industry":"Investment Banking"},
    {"name":"SMBC Nikko","domain":"smbcnikko.com","industry":"Investment Banking"},
    {"name":"CICC","domain":"cicc.com","industry":"Investment Banking"},
    {"name":"Perella Weinberg Partners","domain":"pwpartners.com","industry":"Investment Banking"},
    {"name":"Guggenheim Securities","domain":"guggenheimpartners.com","industry":"Investment Banking"},
    {"name":"Allen & Company","domain":"allenandcompany.com","industry":"Investment Banking"},
    {"name":"LionTree Advisors","domain":"liontree.com","industry":"Investment Banking"},
    {"name":"Qatalyst Partners","domain":"qatalyst.com","industry":"Investment Banking"},
    {"name":"FT Partners","domain":"ftpartners.com","industry":"Investment Banking"},
    {"name":"Raine Group","domain":"rainegroup.com","industry":"Investment Banking"},
    {"name":"M. Klein & Company","domain":"mklein.com","industry":"Investment Banking"},
    {"name":"Greenhill & Co","domain":"greenhill.com","industry":"Investment Banking"},
    {"name":"Duff & Phelps","domain":"duffandphelps.com","industry":"Investment Banking"},
    {"name":"Lincoln International","domain":"lincolninternational.com","industry":"Investment Banking"},
    {"name":"Harris Williams","domain":"harriswilliams.com","industry":"Investment Banking"},
    {"name":"Stout","domain":"stout.com","industry":"Investment Banking"},
    {"name":"Baird","domain":"rwbaird.com","industry":"Investment Banking"},
    {"name":"Stifel","domain":"stifel.com","industry":"Investment Banking"},
    {"name":"Raymond James","domain":"raymondjames.com","industry":"Investment Banking"},
    {"name":"Oppenheimer & Co","domain":"oppenheimer.com","industry":"Investment Banking"},
    {"name":"Cantor Fitzgerald","domain":"cantor.com","industry":"Investment Banking"},
    {"name":"TD Cowen","domain":"cowen.com","industry":"Investment Banking"},
    {"name":"Canaccord Genuity","domain":"canaccordgenuity.com","industry":"Investment Banking"},
    {"name":"Needham & Company","domain":"needham.com","industry":"Investment Banking"},
    {"name":"DA Davidson","domain":"dadavidson.com","industry":"Investment Banking"},
    {"name":"Janney Montgomery Scott","domain":"janney.com","industry":"Investment Banking"},
    {"name":"Stephens Inc","domain":"stephens.com","industry":"Investment Banking"},
    {"name":"KeyBanc Capital Markets","domain":"key.com","industry":"Investment Banking"},
    {"name":"Truist Securities","domain":"truist.com","industry":"Investment Banking"},
    {"name":"Craig-Hallum Capital","domain":"craig-hallum.com","industry":"Investment Banking"},
    {"name":"Lake Street Capital","domain":"lakestreetcapital.com","industry":"Investment Banking"},
    {"name":"Seaport Global","domain":"seaportglobal.com","industry":"Investment Banking"},
    {"name":"JMP Securities","domain":"jmp.com","industry":"Investment Banking"},
    {"name":"Investec","domain":"investec.com","industry":"Investment Banking"},
    {"name":"Peel Hunt","domain":"peelhunt.com","industry":"Investment Banking"},
    {"name":"Liberum Capital","domain":"liberum.com","industry":"Investment Banking"},
    {"name":"Panmure Gordon","domain":"panmure.com","industry":"Investment Banking"},
    {"name":"Intesa Sanpaolo","domain":"intesasanpaolo.com","industry":"Investment Banking"},
    {"name":"Erste Group","domain":"erstegroup.com","industry":"Investment Banking"},
    {"name":"DNB Markets","domain":"dnb.no","industry":"Investment Banking"},
    {"name":"Handelsbanken","domain":"handelsbanken.com","industry":"Investment Banking"},
    {"name":"Rabobank","domain":"rabobank.com","industry":"Investment Banking"},
    {"name":"CIT Group","domain":"cit.com","industry":"Investment Banking"},
    {"name":"B. Riley Securities","domain":"brileyfin.com","industry":"Investment Banking"},
    {"name":"Ladenburg Thalmann","domain":"ladenburg.com","industry":"Investment Banking"},
    {"name":"Sidoti & Company","domain":"sidoti.com","industry":"Investment Banking"},
    {"name":"Loop Capital","domain":"loopcapital.com","industry":"Investment Banking"},
    {"name":"National Bank Financial","domain":"nbc.ca","industry":"Investment Banking"},
    {"name":"CLSA","domain":"clsa.com","industry":"Investment Banking"},
    {"name":"Goodbody","domain":"goodbody.ie","industry":"Investment Banking"},
    {"name":"Chardan Capital","domain":"chardan.com","industry":"Investment Banking"},
    {"name":"Roth Capital Partners","domain":"rothcapital.com","industry":"Investment Banking"},
    {"name":"Numis Securities","domain":"numis.com","industry":"Investment Banking"},
    {"name":"Raiffeisen Bank","domain":"rbinternational.com","industry":"Investment Banking"},
    {"name":"Bradesco BBI","domain":"bradescobbi.com.br","industry":"Investment Banking"},
    {"name":"BTG Pactual","domain":"btgpactual.com","industry":"Investment Banking"},

    {"name":"IBM Consulting","domain":"ibm.com","industry":"Management Consulting"},
    {"name":"Capgemini Invent","domain":"capgemini.com","industry":"Management Consulting"},
    {"name":"Publicis Sapient","domain":"publicissapient.com","industry":"Management Consulting"},
    {"name":"Slalom","domain":"slalom.com","industry":"Management Consulting"},
    {"name":"West Monroe Partners","domain":"westmonroe.com","industry":"Management Consulting"},
    {"name":"Protiviti","domain":"protiviti.com","industry":"Management Consulting"},
    {"name":"Alvarez & Marsal","domain":"alvarezandmarsal.com","industry":"Management Consulting"},
    {"name":"AlixPartners","domain":"alixpartners.com","industry":"Management Consulting"},
    {"name":"Guidehouse","domain":"guidehouse.com","industry":"Management Consulting"},
    {"name":"NERA Economic Consulting","domain":"nera.com","industry":"Management Consulting"},
    {"name":"Charles River Associates","domain":"crai.com","industry":"Management Consulting"},
    {"name":"Simon-Kucher & Partners","domain":"simon-kucher.com","industry":"Management Consulting"},
    {"name":"PA Consulting","domain":"paconsulting.com","industry":"Management Consulting"},
    {"name":"BearingPoint","domain":"bearingpoint.com","industry":"Management Consulting"},
    {"name":"Mercer","domain":"mercer.com","industry":"Management Consulting"},
    {"name":"Willis Towers Watson","domain":"wtwco.com","industry":"Management Consulting"},
    {"name":"Korn Ferry","domain":"kornferry.com","industry":"Management Consulting"},
    {"name":"Spencer Stuart","domain":"spencerstuart.com","industry":"Management Consulting"},
    {"name":"Russell Reynolds Associates","domain":"russellreynolds.com","industry":"Management Consulting"},
    {"name":"Heidrick & Struggles","domain":"heidrick.com","industry":"Management Consulting"},
    {"name":"Egon Zehnder","domain":"egonzehnder.com","industry":"Management Consulting"},
    {"name":"Arthur D. Little","domain":"adlittle.com","industry":"Management Consulting"},
    {"name":"Frost & Sullivan","domain":"frost.com","industry":"Management Consulting"},
    {"name":"Forrester Research","domain":"forrester.com","industry":"Management Consulting"},
    {"name":"Hackett Group","domain":"thehackettgroup.com","industry":"Management Consulting"},
    {"name":"North Highland","domain":"northhighland.com","industry":"Management Consulting"},
    {"name":"ICF International","domain":"icf.com","industry":"Management Consulting"},
    {"name":"Innosight","domain":"innosight.com","industry":"Management Consulting"},
    {"name":"Sia Partners","domain":"sia-partners.com","industry":"Management Consulting"},
    {"name":"OC&C Strategy Consultants","domain":"occstrategy.com","industry":"Management Consulting"},
    {"name":"Marakon","domain":"marakon.com","industry":"Management Consulting"},
    {"name":"Capital Economics","domain":"capitaleconomics.com","industry":"Management Consulting"},
    {"name":"Oxford Economics","domain":"oxfordeconomics.com","industry":"Management Consulting"},
    {"name":"Wood Mackenzie","domain":"woodmac.com","industry":"Management Consulting"},
    {"name":"Exponent","domain":"exponent.com","industry":"Management Consulting"},
    {"name":"Ankura Consulting","domain":"ankura.com","industry":"Management Consulting"},
    {"name":"Compass Lexecon","domain":"compasslexecon.com","industry":"Management Consulting"},
    {"name":"Brattle Group","domain":"brattle.com","industry":"Management Consulting"},
    {"name":"Frontier Economics","domain":"frontier-economics.com","industry":"Management Consulting"},
    {"name":"Oxera","domain":"oxera.com","industry":"Management Consulting"},
    {"name":"Berkeley Research Group","domain":"thinkbrg.com","industry":"Management Consulting"},
    {"name":"Secretariat International","domain":"secretariat-intl.com","industry":"Management Consulting"},
    {"name":"Baker Tilly Advisory","domain":"bakertilly.com","industry":"Management Consulting"},
    {"name":"Plante Moran","domain":"plantemoran.com","industry":"Management Consulting"},
    {"name":"Moss Adams","domain":"mossadams.com","industry":"Management Consulting"},
    {"name":"Wipro","domain":"wipro.com","industry":"Management Consulting"},
    {"name":"Infosys Consulting","domain":"infosys.com","industry":"Management Consulting"},
    {"name":"Cognizant","domain":"cognizant.com","industry":"Management Consulting"},
    {"name":"Tata Consultancy Services","domain":"tcs.com","industry":"Management Consulting"},
    {"name":"HCL Technologies","domain":"hcltech.com","industry":"Management Consulting"},
    {"name":"Thoughtworks","domain":"thoughtworks.com","industry":"Management Consulting"},
    {"name":"EXL Service","domain":"exlservice.com","industry":"Management Consulting"},
    {"name":"WNS Holdings","domain":"wns.com","industry":"Management Consulting"},
    {"name":"EPAM Systems","domain":"epam.com","industry":"Management Consulting"},
    {"name":"Kantar","domain":"kantar.com","industry":"Management Consulting"},
    {"name":"Ipsos","domain":"ipsos.com","industry":"Management Consulting"},
    {"name":"Brunswick Group","domain":"brunswickgroup.com","industry":"Management Consulting"},
    {"name":"Value Partners Consulting","domain":"valuepartners.com","industry":"Management Consulting"},
    {"name":"RAND Corporation","domain":"rand.org","industry":"Management Consulting"},
    {"name":"Mathematica","domain":"mathematica.org","industry":"Management Consulting"},
    {"name":"Public Consulting Group","domain":"publicconsultinggroup.com","industry":"Management Consulting"},
    {"name":"Navigant Consulting","domain":"navigant.com","industry":"Management Consulting"},
    {"name":"Crowe Advisory","domain":"crowe.com","industry":"Management Consulting"},
    {"name":"Grant Thornton Advisory","domain":"grantthornton.com","industry":"Management Consulting"},
    {"name":"RSM Advisory","domain":"rsmus.com","industry":"Management Consulting"},
    {"name":"BDO Advisory","domain":"bdo.com","industry":"Management Consulting"},
    {"name":"Luxoft","domain":"luxoft.com","industry":"Management Consulting"},

    {"name":"Vista Equity Partners","domain":"vistaequitypartners.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Francisco Partners","domain":"franciscopartners.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Thoma Bravo","domain":"thomabravo.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Hellman & Friedman","domain":"hf.com","industry":"Private Equity & Hedge Funds"},
    {"name":"GTCR","domain":"gtcr.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Leonard Green & Partners","domain":"leonardgreen.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Permira","domain":"permira.com","industry":"Private Equity & Hedge Funds"},
    {"name":"CVC Capital Partners","domain":"cvc.com","industry":"Private Equity & Hedge Funds"},
    {"name":"EQT Partners","domain":"eqtgroup.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Cinven","domain":"cinven.com","industry":"Private Equity & Hedge Funds"},
    {"name":"BC Partners","domain":"bcpartners.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Apax Partners","domain":"apax.com","industry":"Private Equity & Hedge Funds"},
    {"name":"3i Group","domain":"3i.com","industry":"Private Equity & Hedge Funds"},
    {"name":"PAI Partners","domain":"paipartners.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Nordic Capital","domain":"nordiccapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Ardian","domain":"ardian.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Partners Group","domain":"partnersgroup.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Intermediate Capital Group","domain":"icgam.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Ares Management","domain":"aresmgmt.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Blue Owl Capital","domain":"blueowl.com","industry":"Private Equity & Hedge Funds"},
    {"name":"HIG Capital","domain":"higcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Platinum Equity","domain":"platinumequity.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Cerberus Capital","domain":"cerberuscapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Fortress Investment Group","domain":"fortress.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Oaktree Capital","domain":"oaktreecapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Centerbridge Partners","domain":"centerbridge.com","industry":"Private Equity & Hedge Funds"},
    {"name":"New Mountain Capital","domain":"newmountaincapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Summit Partners","domain":"summitpartners.com","industry":"Private Equity & Hedge Funds"},
    {"name":"TA Associates","domain":"ta.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Riverside Company","domain":"riversidecompany.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Insight Partners","domain":"insightpartners.com","industry":"Private Equity & Hedge Funds"},
    {"name":"L Catterton","domain":"lcatterton.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Roark Capital Group","domain":"roarkcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Bridgepoint","domain":"bridgepoint.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Hg Capital","domain":"hgcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Eurazeo","domain":"eurazeo.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Wendel","domain":"wendelgroup.com","industry":"Private Equity & Hedge Funds"},
    {"name":"American Securities","domain":"american-securities.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Sycamore Partners","domain":"sycamorepartners.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Starwood Capital","domain":"starwoodcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Bridgewater Associates","domain":"bridgewater.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Renaissance Technologies","domain":"rentec.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Two Sigma","domain":"twosigma.com","industry":"Private Equity & Hedge Funds"},
    {"name":"DE Shaw","domain":"deshaw.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Citadel","domain":"citadel.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Millennium Management","domain":"mlp.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Point72","domain":"point72.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Coatue Management","domain":"coatue.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Tiger Global","domain":"tigerglobal.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Pershing Square","domain":"pershingsquare.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Third Point","domain":"thirdpointllc.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Elliott Management","domain":"elliottmgmt.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Baupost Group","domain":"baupost.com","industry":"Private Equity & Hedge Funds"},
    {"name":"AQR Capital","domain":"aqr.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Man Group","domain":"man.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Winton Group","domain":"winton.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Farallon Capital","domain":"faralloncapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Angelo Gordon","domain":"angelogordon.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Lone Pine Capital","domain":"lonepinecapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Viking Global","domain":"vikingglobal.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Appaloosa Management","domain":"appaloosamgmt.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Greenlight Capital","domain":"greenlightcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Canyon Capital","domain":"canyoncapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Avenue Capital","domain":"avenuecapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Glenview Capital","domain":"glenviewcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"King Street Capital","domain":"kingstreetcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Maverick Capital","domain":"maverickcap.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Anchorage Capital","domain":"anchoragecapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Soros Fund Management","domain":"soros.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Dragoneer Investment Group","domain":"dragoneer.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Durable Capital Partners","domain":"durablecapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Searchlight Capital","domain":"searchlightcap.com","industry":"Private Equity & Hedge Funds"},
    {"name":"ABRY Partners","domain":"abry.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Accel-KKR","domain":"accelkkr.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Golub Capital","domain":"golubcapital.com","industry":"Private Equity & Hedge Funds"},
    {"name":"Antares Capital","domain":"antarescapital.com","industry":"Private Equity & Hedge Funds"},

    {"name":"Oracle","domain":"oracle.com","industry":"Big Tech"},
    {"name":"Intel","domain":"intel.com","industry":"Big Tech"},
    {"name":"SAP","domain":"sap.com","industry":"Big Tech"},
    {"name":"Qualcomm","domain":"qualcomm.com","industry":"Big Tech"},
    {"name":"Texas Instruments","domain":"ti.com","industry":"Big Tech"},
    {"name":"AMD","domain":"amd.com","industry":"Big Tech"},
    {"name":"Broadcom","domain":"broadcom.com","industry":"Big Tech"},
    {"name":"Cisco","domain":"cisco.com","industry":"Big Tech"},
    {"name":"HP","domain":"hp.com","industry":"Big Tech"},
    {"name":"Dell","domain":"dell.com","industry":"Big Tech"},
    {"name":"VMware","domain":"vmware.com","industry":"Big Tech"},
    {"name":"ServiceNow","domain":"servicenow.com","industry":"Big Tech"},
    {"name":"Workday","domain":"workday.com","industry":"Big Tech"},
    {"name":"Snowflake","domain":"snowflake.com","industry":"Big Tech"},
    {"name":"Datadog","domain":"datadoghq.com","industry":"Big Tech"},
    {"name":"Cloudflare","domain":"cloudflare.com","industry":"Big Tech"},
    {"name":"Shopify","domain":"shopify.com","industry":"Big Tech"},
    {"name":"Stripe","domain":"stripe.com","industry":"Big Tech"},
    {"name":"Palantir","domain":"palantir.com","industry":"Big Tech"},
    {"name":"Databricks","domain":"databricks.com","industry":"Big Tech"},
    {"name":"Dropbox","domain":"dropbox.com","industry":"Big Tech"},
    {"name":"Box","domain":"box.com","industry":"Big Tech"},
    {"name":"Zoom","domain":"zoom.us","industry":"Big Tech"},
    {"name":"Twitter / X","domain":"x.com","industry":"Big Tech"},
    {"name":"Spotify","domain":"spotify.com","industry":"Big Tech"},
    {"name":"Airbnb","domain":"airbnb.com","industry":"Big Tech"},
    {"name":"Uber","domain":"uber.com","industry":"Big Tech"},
    {"name":"Lyft","domain":"lyft.com","industry":"Big Tech"},
    {"name":"DoorDash","domain":"doordash.com","industry":"Big Tech"},
    {"name":"Coinbase","domain":"coinbase.com","industry":"Big Tech"},
    {"name":"Robinhood","domain":"robinhood.com","industry":"Big Tech"},
    {"name":"Plaid","domain":"plaid.com","industry":"Big Tech"},
    {"name":"Block","domain":"block.xyz","industry":"Big Tech"},
    {"name":"PayPal","domain":"paypal.com","industry":"Big Tech"},
    {"name":"eBay","domain":"ebay.com","industry":"Big Tech"},
    {"name":"Booking.com","domain":"booking.com","industry":"Big Tech"},
    {"name":"Expedia","domain":"expedia.com","industry":"Big Tech"},
    {"name":"Snap","domain":"snap.com","industry":"Big Tech"},
    {"name":"Reddit","domain":"reddit.com","industry":"Big Tech"},
    {"name":"Discord","domain":"discord.com","industry":"Big Tech"},
    {"name":"Roblox","domain":"roblox.com","industry":"Big Tech"},
    {"name":"Unity Technologies","domain":"unity.com","industry":"Big Tech"},
    {"name":"Epic Games","domain":"epicgames.com","industry":"Big Tech"},
    {"name":"Electronic Arts","domain":"ea.com","industry":"Big Tech"},
    {"name":"Activision Blizzard","domain":"activisionblizzard.com","industry":"Big Tech"},
    {"name":"Riot Games","domain":"riotgames.com","industry":"Big Tech"},
    {"name":"ByteDance","domain":"bytedance.com","industry":"Big Tech"},
    {"name":"Baidu","domain":"baidu.com","industry":"Big Tech"},
    {"name":"Alibaba","domain":"alibaba.com","industry":"Big Tech"},
    {"name":"Tencent","domain":"tencent.com","industry":"Big Tech"},
    {"name":"Samsung","domain":"samsung.com","industry":"Big Tech"},
    {"name":"TSMC","domain":"tsmc.com","industry":"Big Tech"},
    {"name":"ASML","domain":"asml.com","industry":"Big Tech"},
    {"name":"Arm Holdings","domain":"arm.com","industry":"Big Tech"},
    {"name":"Micron Technology","domain":"micron.com","industry":"Big Tech"},
    {"name":"Western Digital","domain":"westerndigital.com","industry":"Big Tech"},
    {"name":"CrowdStrike","domain":"crowdstrike.com","industry":"Big Tech"},
    {"name":"Palo Alto Networks","domain":"paloaltonetworks.com","industry":"Big Tech"},
    {"name":"Fortinet","domain":"fortinet.com","industry":"Big Tech"},
    {"name":"Zscaler","domain":"zscaler.com","industry":"Big Tech"},
    {"name":"Okta","domain":"okta.com","industry":"Big Tech"},
    {"name":"HubSpot","domain":"hubspot.com","industry":"Big Tech"},
    {"name":"Zendesk","domain":"zendesk.com","industry":"Big Tech"},
    {"name":"Atlassian","domain":"atlassian.com","industry":"Big Tech"},
    {"name":"MongoDB","domain":"mongodb.com","industry":"Big Tech"},
    {"name":"Elastic","domain":"elastic.co","industry":"Big Tech"},
    {"name":"Splunk","domain":"splunk.com","industry":"Big Tech"},
    {"name":"Veeva Systems","domain":"veeva.com","industry":"Big Tech"},
    {"name":"Procore Technologies","domain":"procore.com","industry":"Big Tech"},
    {"name":"Toast","domain":"toasttab.com","industry":"Big Tech"},
    {"name":"Twilio","domain":"twilio.com","industry":"Big Tech"},
    {"name":"New Relic","domain":"newrelic.com","industry":"Big Tech"},
    {"name":"HashiCorp","domain":"hashicorp.com","industry":"Big Tech"},
    {"name":"Confluent","domain":"confluent.io","industry":"Big Tech"},
    {"name":"Pinterest","domain":"pinterest.com","industry":"Big Tech"},
    {"name":"Etsy","domain":"etsy.com","industry":"Big Tech"},
    {"name":"Wayfair","domain":"wayfair.com","industry":"Big Tech"},
    {"name":"Instacart","domain":"instacart.com","industry":"Big Tech"},
    {"name":"Chewy","domain":"chewy.com","industry":"Big Tech"},

    {"name":"Baker Tilly","domain":"bakertilly.com","industry":"Accounting"},
    {"name":"Plante Moran","domain":"plantemoran.com","industry":"Accounting"},
    {"name":"Moss Adams","domain":"mossadams.com","industry":"Accounting"},
    {"name":"CLA (CliftonLarsonAllen)","domain":"claconnect.com","industry":"Accounting"},
    {"name":"Wipfli","domain":"wipfli.com","industry":"Accounting"},
    {"name":"Eide Bailly","domain":"eidebailly.com","industry":"Accounting"},
    {"name":"Marcum","domain":"marcumllp.com","industry":"Accounting"},
    {"name":"WithumSmith+Brown","domain":"withum.com","industry":"Accounting"},
    {"name":"Citrin Cooperman","domain":"citrincooperman.com","industry":"Accounting"},
    {"name":"Armanino","domain":"armanino.com","industry":"Accounting"},
    {"name":"Weaver","domain":"weaver.com","industry":"Accounting"},
    {"name":"Sikich","domain":"sikich.com","industry":"Accounting"},
    {"name":"Cherry Bekaert","domain":"cbh.com","industry":"Accounting"},
    {"name":"CohnReznick","domain":"cohnreznick.com","industry":"Accounting"},
    {"name":"CBIZ","domain":"cbiz.com","industry":"Accounting"},
    {"name":"Forvis Mazars","domain":"forvismazars.com","industry":"Accounting"},
    {"name":"Mazars","domain":"mazars.com","industry":"Accounting"},
    {"name":"PKF International","domain":"pkf.com","industry":"Accounting"},
    {"name":"Moore Global","domain":"moore-global.com","industry":"Accounting"},
    {"name":"Nexia International","domain":"nexia.com","industry":"Accounting"},
    {"name":"HLB International","domain":"hlbi.com","industry":"Accounting"},
    {"name":"BKR International","domain":"bkr.com","industry":"Accounting"},
    {"name":"Kreston Global","domain":"kreston.com","industry":"Accounting"},
    {"name":"Allinial Global","domain":"allinial.com","industry":"Accounting"},
    {"name":"AGN International","domain":"agn.org","industry":"Accounting"},
    {"name":"MGO","domain":"mgocpa.com","industry":"Accounting"},
    {"name":"Friedman LLP","domain":"friedmanllp.com","industry":"Accounting"},
    {"name":"Anchin","domain":"anchin.com","industry":"Accounting"},
    {"name":"Rehmann","domain":"rehmann.com","industry":"Accounting"},
    {"name":"Aprio","domain":"aprio.com","industry":"Accounting"},
    {"name":"Grassi","domain":"grassicpas.com","industry":"Accounting"},
    {"name":"Kaufman Rossin","domain":"kaufmanrossin.com","industry":"Accounting"},
    {"name":"Withum Smith+Brown","domain":"withum.com","industry":"Accounting"},
    {"name":"Mayer Hoffman McCann","domain":"mhmcpa.com","industry":"Accounting"},
    {"name":"Schneider Downs","domain":"schneiderdowns.com","industry":"Accounting"},
    {"name":"Dixon Hughes Goodman","domain":"dhg.com","industry":"Accounting"},
    {"name":"Lurie LLP","domain":"luriecpa.com","industry":"Accounting"},
    {"name":"Plante & Moran","domain":"plantemoran.com","industry":"Accounting"},
    {"name":"Postlethwaite & Netterville","domain":"pncpa.com","industry":"Accounting"},
    {"name":"Carr, Riggs & Ingram","domain":"cricpa.com","industry":"Accounting"},
    {"name":"Rea & Associates","domain":"reacpa.com","industry":"Accounting"},
    {"name":"Bonadio Group","domain":"bonadio.com","industry":"Accounting"},
    {"name":"Frazier & Deeter","domain":"frazierdeeter.com","industry":"Accounting"},
    {"name":"Anders CPAs","domain":"anderscpa.com","industry":"Accounting"},
    {"name":"Audit Analytics","domain":"auditanalytics.com","industry":"Accounting"},
    {"name":"Deloitte Touche Tohmatsu","domain":"deloitte.com","industry":"Accounting"},
    {"name":"PricewaterhouseCoopers","domain":"pwc.com","industry":"Accounting"},
    {"name":"Ernst & Young","domain":"ey.com","industry":"Accounting"},
    {"name":"KPMG","domain":"kpmg.com","industry":"Accounting"},
    {"name":"Grant Thornton","domain":"grantthornton.com","industry":"Accounting"},
    {"name":"BDO","domain":"bdo.com","industry":"Accounting"},
    {"name":"RSM","domain":"rsmus.com","industry":"Accounting"},
    {"name":"Crowe","domain":"crowe.com","industry":"Accounting"},
    {"name":"Hogan Taylor","domain":"hogantaylor.com","industry":"Accounting"},
    {"name":"Whitley Penn","domain":"whitleypenn.com","industry":"Accounting"},
    {"name":"Aronson LLC","domain":"aronsonllc.com","industry":"Accounting"},
    {"name":"Berdon LLP","domain":"berdonllp.com","industry":"Accounting"},
    {"name":"Caliber Imaging","domain":"calibercpa.com","industry":"Accounting"},
    {"name":"Hancock Askew","domain":"hancockaskew.com","industry":"Accounting"},
    {"name":"YHB","domain":"yhb.com","industry":"Accounting"},
    {"name":"Citrin Cooperman","domain":"citrincooperman.com","industry":"Accounting"},

    {"name":"Kirkland & Ellis","domain":"kirkland.com","industry":"Law"},
    {"name":"Latham & Watkins","domain":"lw.com","industry":"Law"},
    {"name":"Skadden Arps","domain":"skadden.com","industry":"Law"},
    {"name":"Sullivan & Cromwell","domain":"sullcrom.com","industry":"Law"},
    {"name":"Wachtell Lipton","domain":"wlrk.com","industry":"Law"},
    {"name":"Davis Polk & Wardwell","domain":"davispolk.com","industry":"Law"},
    {"name":"Cravath Swaine & Moore","domain":"cravath.com","industry":"Law"},
    {"name":"Simpson Thacher & Bartlett","domain":"stblaw.com","industry":"Law"},
    {"name":"Weil Gotshal & Manges","domain":"weil.com","industry":"Law"},
    {"name":"Cleary Gottlieb","domain":"clearygottlieb.com","industry":"Law"},
    {"name":"Milbank","domain":"milbank.com","industry":"Law"},
    {"name":"Paul Weiss","domain":"paulweiss.com","industry":"Law"},
    {"name":"Willkie Farr & Gallagher","domain":"willkie.com","industry":"Law"},
    {"name":"Debevoise & Plimpton","domain":"debevoise.com","industry":"Law"},
    {"name":"White & Case","domain":"whitecase.com","industry":"Law"},
    {"name":"Freshfields","domain":"freshfields.com","industry":"Law"},
    {"name":"Linklaters","domain":"linklaters.com","industry":"Law"},
    {"name":"Allen & Overy","domain":"allenovery.com","industry":"Law"},
    {"name":"Clifford Chance","domain":"cliffordchance.com","industry":"Law"},
    {"name":"Slaughter and May","domain":"slaughterandmay.com","industry":"Law"},
    {"name":"Herbert Smith Freehills","domain":"hsf.com","industry":"Law"},
    {"name":"Ashurst","domain":"ashurst.com","industry":"Law"},
    {"name":"Norton Rose Fulbright","domain":"nortonrosefulbright.com","industry":"Law"},
    {"name":"Baker McKenzie","domain":"bakermckenzie.com","industry":"Law"},
    {"name":"DLA Piper","domain":"dlapiper.com","industry":"Law"},
    {"name":"Greenberg Traurig","domain":"gtlaw.com","industry":"Law"},
    {"name":"Jones Day","domain":"jonesday.com","industry":"Law"},
    {"name":"Sidley Austin","domain":"sidley.com","industry":"Law"},
    {"name":"McDermott Will & Emery","domain":"mwe.com","industry":"Law"},
    {"name":"Gibson Dunn","domain":"gibsondunn.com","industry":"Law"},
    {"name":"O''Melveny & Myers","domain":"omm.com","industry":"Law"},
    {"name":"Orrick","domain":"orrick.com","industry":"Law"},
    {"name":"Hogan Lovells","domain":"hoganlovells.com","industry":"Law"},
    {"name":"Reed Smith","domain":"reedsmith.com","industry":"Law"},
    {"name":"Akin Gump","domain":"akingump.com","industry":"Law"},
    {"name":"Winston & Strawn","domain":"winston.com","industry":"Law"},
    {"name":"Mayer Brown","domain":"mayerbrown.com","industry":"Law"},
    {"name":"Dechert","domain":"dechert.com","industry":"Law"},
    {"name":"Vinson & Elkins","domain":"velaw.com","industry":"Law"},
    {"name":"King & Spalding","domain":"kslaw.com","industry":"Law"},
    {"name":"Paul Hastings","domain":"paulhastings.com","industry":"Law"},
    {"name":"Ropes & Gray","domain":"ropesgray.com","industry":"Law"},
    {"name":"Morgan Lewis & Bockius","domain":"morganlewis.com","industry":"Law"},
    {"name":"Proskauer Rose","domain":"proskauer.com","industry":"Law"},
    {"name":"Foley & Lardner","domain":"foley.com","industry":"Law"},
    {"name":"Cooley LLP","domain":"cooley.com","industry":"Law"},
    {"name":"Goodwin Procter","domain":"goodwinlaw.com","industry":"Law"},
    {"name":"Wilson Sonsini","domain":"wsgr.com","industry":"Law"},
    {"name":"Fenwick & West","domain":"fenwick.com","industry":"Law"},
    {"name":"Gunderson Dettmer","domain":"gunder.com","industry":"Law"},
    {"name":"Duane Morris","domain":"duanemorris.com","industry":"Law"},
    {"name":"Pillsbury Winthrop","domain":"pillsburylaw.com","industry":"Law"},
    {"name":"Nixon Peabody","domain":"nixonpeabody.com","industry":"Law"},
    {"name":"Holland & Knight","domain":"hklaw.com","industry":"Law"},
    {"name":"Blank Rome","domain":"blankrome.com","industry":"Law"},
    {"name":"Seyfarth Shaw","domain":"seyfarth.com","industry":"Law"},
    {"name":"Littler Mendelson","domain":"littler.com","industry":"Law"},
    {"name":"Ogletree Deakins","domain":"ogletree.com","industry":"Law"},
    {"name":"Katten Muchin Rosenman","domain":"katten.com","industry":"Law"},
    {"name":"Polsinelli","domain":"polsinelli.com","industry":"Law"},
    {"name":"Squire Patton Boggs","domain":"squirepattonboggs.com","industry":"Law"},
    {"name":"Dentons","domain":"dentons.com","industry":"Law"},
    {"name":"CMS Law","domain":"cms.law","industry":"Law"},
    {"name":"Taylor Wessing","domain":"taylorwessing.com","industry":"Law"},
    {"name":"Mishcon de Reya","domain":"mishcon.com","industry":"Law"},
    {"name":"Travers Smith","domain":"traverssmith.com","industry":"Law"},
    {"name":"Macfarlanes","domain":"macfarlanes.com","industry":"Law"},
    {"name":"Eversheds Sutherland","domain":"eversheds-sutherland.com","industry":"Law"},
    {"name":"Steptoe & Johnson","domain":"steptoe.com","industry":"Law"},
    {"name":"Fish & Richardson","domain":"fr.com","industry":"Law"},
    {"name":"Finnegan Henderson","domain":"finnegan.com","industry":"Law"},
    {"name":"Bryan Cave Leighton Paisner","domain":"bclplaw.com","industry":"Law"},
    {"name":"Hunton Andrews Kurth","domain":"huntonak.com","industry":"Law"},
    {"name":"Ice Miller","domain":"icemiller.com","industry":"Law"},
    {"name":"Buchanan Ingersoll & Rooney","domain":"bipc.com","industry":"Law"},
    {"name":"Faegre Drinker","domain":"faegredrinker.com","industry":"Law"},
    {"name":"Mintz Levin","domain":"mintz.com","industry":"Law"},
    {"name":"Shearman & Sterling","domain":"shearman.com","industry":"Law"},
    {"name":"Stroock & Stroock","domain":"stroock.com","industry":"Law"},
    {"name":"Cahill Gordon & Reindel","domain":"cahill.com","industry":"Law"},

    {"name":"Johnson & Johnson","domain":"jnj.com","industry":"Biotech & Pharma"},
    {"name":"Pfizer","domain":"pfizer.com","industry":"Biotech & Pharma"},
    {"name":"AstraZeneca","domain":"astrazeneca.com","industry":"Biotech & Pharma"},
    {"name":"Novartis","domain":"novartis.com","industry":"Biotech & Pharma"},
    {"name":"Roche","domain":"roche.com","industry":"Biotech & Pharma"},
    {"name":"Merck & Co","domain":"merck.com","industry":"Biotech & Pharma"},
    {"name":"Bristol-Myers Squibb","domain":"bms.com","industry":"Biotech & Pharma"},
    {"name":"AbbVie","domain":"abbvie.com","industry":"Biotech & Pharma"},
    {"name":"Eli Lilly","domain":"lilly.com","industry":"Biotech & Pharma"},
    {"name":"Amgen","domain":"amgen.com","industry":"Biotech & Pharma"},
    {"name":"Gilead Sciences","domain":"gilead.com","industry":"Biotech & Pharma"},
    {"name":"Biogen","domain":"biogen.com","industry":"Biotech & Pharma"},
    {"name":"Regeneron","domain":"regeneron.com","industry":"Biotech & Pharma"},
    {"name":"Moderna","domain":"modernatx.com","industry":"Biotech & Pharma"},
    {"name":"Vertex Pharmaceuticals","domain":"vrtx.com","industry":"Biotech & Pharma"},
    {"name":"BioNTech","domain":"biontech.com","industry":"Biotech & Pharma"},
    {"name":"Genentech","domain":"gene.com","industry":"Biotech & Pharma"},
    {"name":"Sanofi","domain":"sanofi.com","industry":"Biotech & Pharma"},
    {"name":"GlaxoSmithKline","domain":"gsk.com","industry":"Biotech & Pharma"},
    {"name":"Bayer","domain":"bayer.com","industry":"Biotech & Pharma"},
    {"name":"Takeda","domain":"takeda.com","industry":"Biotech & Pharma"},
    {"name":"Astellas","domain":"astellas.com","industry":"Biotech & Pharma"},
    {"name":"Daiichi Sankyo","domain":"daiichisankyo.com","industry":"Biotech & Pharma"},
    {"name":"Novo Nordisk","domain":"novonordisk.com","industry":"Biotech & Pharma"},
    {"name":"UCB","domain":"ucb.com","industry":"Biotech & Pharma"},
    {"name":"Alexion Pharmaceuticals","domain":"alexion.com","industry":"Biotech & Pharma"},
    {"name":"Alnylam Pharmaceuticals","domain":"alnylam.com","industry":"Biotech & Pharma"},
    {"name":"BioMarin","domain":"biomarin.com","industry":"Biotech & Pharma"},
    {"name":"Incyte","domain":"incyte.com","industry":"Biotech & Pharma"},
    {"name":"Seagen","domain":"seagen.com","industry":"Biotech & Pharma"},
    {"name":"Illumina","domain":"illumina.com","industry":"Biotech & Pharma"},
    {"name":"10x Genomics","domain":"10xgenomics.com","industry":"Biotech & Pharma"},
    {"name":"Pacific Biosciences","domain":"pacb.com","industry":"Biotech & Pharma"},
    {"name":"Exact Sciences","domain":"exactsciences.com","industry":"Biotech & Pharma"},
    {"name":"Guardant Health","domain":"guardanthealth.com","industry":"Biotech & Pharma"},
    {"name":"Foundation Medicine","domain":"foundationmedicine.com","industry":"Biotech & Pharma"},
    {"name":"Twist Bioscience","domain":"twistbioscience.com","industry":"Biotech & Pharma"},
    {"name":"Recursion Pharmaceuticals","domain":"recursion.com","industry":"Biotech & Pharma"},
    {"name":"Relay Therapeutics","domain":"relaytx.com","industry":"Biotech & Pharma"},
    {"name":"Karuna Therapeutics","domain":"karunatx.com","industry":"Biotech & Pharma"},
    {"name":"Sage Therapeutics","domain":"sagerx.com","industry":"Biotech & Pharma"},
    {"name":"Blueprint Medicines","domain":"blueprintmedicines.com","industry":"Biotech & Pharma"},
    {"name":"Global Blood Therapeutics","domain":"gbt.com","industry":"Biotech & Pharma"},
    {"name":"Ultragenyx","domain":"ultragenyx.com","industry":"Biotech & Pharma"},
    {"name":"Ionis Pharmaceuticals","domain":"ionispharma.com","industry":"Biotech & Pharma"},
    {"name":"Intellia Therapeutics","domain":"intelliatx.com","industry":"Biotech & Pharma"},
    {"name":"Editas Medicine","domain":"editasmedicine.com","industry":"Biotech & Pharma"},
    {"name":"CRISPR Therapeutics","domain":"crisprtx.com","industry":"Biotech & Pharma"},
    {"name":"Beam Therapeutics","domain":"beamtx.com","industry":"Biotech & Pharma"},
    {"name":"Passage Bio","domain":"passagebio.com","industry":"Biotech & Pharma"},
    {"name":"Translate Bio","domain":"translate.bio","industry":"Biotech & Pharma"},
    {"name":"Praxis Precision Medicine","domain":"praxismedicines.com","industry":"Biotech & Pharma"},
    {"name":"Arrowhead Pharmaceuticals","domain":"arrowheadpharma.com","industry":"Biotech & Pharma"},
    {"name":"Halozyme Therapeutics","domain":"halozyme.com","industry":"Biotech & Pharma"},
    {"name":"Radius Health","domain":"radiuspharm.com","industry":"Biotech & Pharma"},
    {"name":"Protagonist Therapeutics","domain":"protagonist-inc.com","industry":"Biotech & Pharma"},
    {"name":"Karuna Therapeutics","domain":"karunatx.com","industry":"Biotech & Pharma"},
    {"name":"Bicycle Therapeutics","domain":"bicycletherapeutics.com","industry":"Biotech & Pharma"},
    {"name":"Arena Pharmaceuticals","domain":"arenapharm.com","industry":"Biotech & Pharma"},
    {"name":"Sangamo Therapeutics","domain":"sangamo.com","industry":"Biotech & Pharma"},
    {"name":"Protagonist Therapeutics","domain":"protagonist-inc.com","industry":"Biotech & Pharma"},
    {"name":"Neurocrine Biosciences","domain":"neurocrine.com","industry":"Biotech & Pharma"},
    {"name":"Esperion Therapeutics","domain":"esperion.com","industry":"Biotech & Pharma"},
    {"name":"Kodiak Sciences","domain":"kodiak.com","industry":"Biotech & Pharma"},
    {"name":"Xenon Pharmaceuticals","domain":"xenon-pharma.com","industry":"Biotech & Pharma"},
    {"name":"SpringWorks Therapeutics","domain":"springworkstx.com","industry":"Biotech & Pharma"},
    {"name":"Merus","domain":"merus.nl","industry":"Biotech & Pharma"},
    {"name":"Imago BioSciences","domain":"imagobiosciences.com","industry":"Biotech & Pharma"},
    {"name":"Centessa Pharmaceuticals","domain":"centessa.com","industry":"Biotech & Pharma"},
    {"name":"Syndax Pharmaceuticals","domain":"syndax.com","industry":"Biotech & Pharma"},
    {"name":"Kymera Therapeutics","domain":"kymeratherapeutics.com","industry":"Biotech & Pharma"},
    {"name":"C4 Therapeutics","domain":"c4therapeutics.com","industry":"Biotech & Pharma"},
    {"name":"Prelude Therapeutics","domain":"preludetx.com","industry":"Biotech & Pharma"},
    {"name":"Day One Biopharmaceuticals","domain":"dayonebio.com","industry":"Biotech & Pharma"},
    {"name":"Inhibrx","domain":"inhibrx.com","industry":"Biotech & Pharma"},
    {"name":"Celldex Therapeutics","domain":"celldex.com","industry":"Biotech & Pharma"},
    {"name":"Merus","domain":"merus.nl","industry":"Biotech & Pharma"},

    {"name":"Sequoia Capital","domain":"sequoiacap.com","industry":"Venture Capital"},
    {"name":"Andreessen Horowitz","domain":"a16z.com","industry":"Venture Capital"},
    {"name":"Accel","domain":"accel.com","industry":"Venture Capital"},
    {"name":"Kleiner Perkins","domain":"kleinerperkins.com","industry":"Venture Capital"},
    {"name":"Benchmark Capital","domain":"benchmark.com","industry":"Venture Capital"},
    {"name":"Founders Fund","domain":"foundersfund.com","industry":"Venture Capital"},
    {"name":"Lightspeed Venture Partners","domain":"lsvp.com","industry":"Venture Capital"},
    {"name":"Bessemer Venture Partners","domain":"bvp.com","industry":"Venture Capital"},
    {"name":"Index Ventures","domain":"indexventures.com","industry":"Venture Capital"},
    {"name":"General Catalyst","domain":"generalcatalyst.com","industry":"Venture Capital"},
    {"name":"NEA","domain":"nea.com","industry":"Venture Capital"},
    {"name":"IVP","domain":"ivp.com","industry":"Venture Capital"},
    {"name":"Battery Ventures","domain":"battery.com","industry":"Venture Capital"},
    {"name":"GGV Capital","domain":"ggvc.com","industry":"Venture Capital"},
    {"name":"Greylock Partners","domain":"greylock.com","industry":"Venture Capital"},
    {"name":"Spark Capital","domain":"sparkcapital.com","industry":"Venture Capital"},
    {"name":"Redpoint Ventures","domain":"redpoint.com","industry":"Venture Capital"},
    {"name":"Union Square Ventures","domain":"usv.com","industry":"Venture Capital"},
    {"name":"First Round Capital","domain":"firstround.com","industry":"Venture Capital"},
    {"name":"Flatiron Health","domain":"flatiron.com","industry":"Venture Capital"},
    {"name":"Social Capital","domain":"socialcapital.com","industry":"Venture Capital"},
    {"name":"SoftBank Vision Fund","domain":"softbank.com","industry":"Venture Capital"},
    {"name":"DST Global","domain":"dst.global","industry":"Venture Capital"},
    {"name":"Iconiq Capital","domain":"iconiqcapital.com","industry":"Venture Capital"},
    {"name":"Ribbit Capital","domain":"ribbitcap.com","industry":"Venture Capital"},
    {"name":"Coatue Ventures","domain":"coatue.com","industry":"Venture Capital"},
    {"name":"Tiger Global Ventures","domain":"tigerglobal.com","industry":"Venture Capital"},
    {"name":"Craft Ventures","domain":"craft.co","industry":"Venture Capital"},
    {"name":"Initialized Capital","domain":"initialized.com","industry":"Venture Capital"},
    {"name":"Y Combinator","domain":"ycombinator.com","industry":"Venture Capital"},
    {"name":"500 Global","domain":"500.co","industry":"Venture Capital"},
    {"name":"Techstars","domain":"techstars.com","industry":"Venture Capital"},
    {"name":"Felicis Ventures","domain":"felicis.com","industry":"Venture Capital"},
    {"name":"CRV","domain":"crv.com","industry":"Venture Capital"},
    {"name":"Matrix Partners","domain":"matrixpartners.com","industry":"Venture Capital"},
    {"name":"DCVC","domain":"dcvc.com","industry":"Venture Capital"},
    {"name":"Lux Capital","domain":"luxcapital.com","industry":"Venture Capital"},
    {"name":"Obvious Ventures","domain":"obvious.com","industry":"Venture Capital"},
    {"name":"Andreessen Horowitz Bio","domain":"a16z.com","industry":"Venture Capital"},
    {"name":"GV (Google Ventures)","domain":"gv.com","industry":"Venture Capital"},
    {"name":"Intel Capital","domain":"intelcapital.com","industry":"Venture Capital"},
    {"name":"Microsoft Ventures","domain":"m12.vc","industry":"Venture Capital"},
    {"name":"Salesforce Ventures","domain":"salesforceventures.com","industry":"Venture Capital"},
    {"name":"Comcast Ventures","domain":"comcastventures.com","industry":"Venture Capital"},
    {"name":"Dell Technologies Capital","domain":"delltechnologies.com","industry":"Venture Capital"},
    {"name":"Qualcomm Ventures","domain":"qualcommventures.com","industry":"Venture Capital"},
    {"name":"Samsung NEXT","domain":"samsungnext.com","industry":"Venture Capital"},
    {"name":"SV Angel","domain":"svangel.com","industry":"Venture Capital"},
    {"name":"Box Group","domain":"boxgroup.com","industry":"Venture Capital"},
    {"name":"Uncork Capital","domain":"uncorkcapital.com","industry":"Venture Capital"},
    {"name":"Lead Edge Capital","domain":"leadedgecapital.com","industry":"Venture Capital"},
    {"name":"TCV","domain":"tcv.com","industry":"Venture Capital"},
    {"name":"Vista Equity Growth","domain":"vistaequitypartners.com","industry":"Venture Capital"},
    {"name":"Stripes","domain":"stripesgroup.com","industry":"Venture Capital"},
    {"name":"Emergence Capital","domain":"emcap.com","industry":"Venture Capital"},
    {"name":"OpenView","domain":"openviewpartners.com","industry":"Venture Capital"},
    {"name":"Sapphire Ventures","domain":"sapphireventures.com","industry":"Venture Capital"},
    {"name":"Meritech Capital","domain":"meritechcapital.com","industry":"Venture Capital"},
    {"name":"Norwest Venture Partners","domain":"nvp.com","industry":"Venture Capital"},
    {"name":"Menlo Ventures","domain":"menlovc.com","industry":"Venture Capital"},
    {"name":"August Capital","domain":"augustcap.com","industry":"Venture Capital"},
    {"name":"Canaan Partners","domain":"canaan.com","industry":"Venture Capital"},
    {"name":"Shasta Ventures","domain":"shastaventures.com","industry":"Venture Capital"},
    {"name":"Formation 8","domain":"formation8.com","industry":"Venture Capital"},
    {"name":"Andreessen Horowitz a16z crypto","domain":"a16zcrypto.com","industry":"Venture Capital"},
    {"name":"Paradigm","domain":"paradigm.xyz","industry":"Venture Capital"},
    {"name":"Multicoin Capital","domain":"multicoin.capital","industry":"Venture Capital"},
    {"name":"Haun Ventures","domain":"haun.com","industry":"Venture Capital"},
    {"name":"Pantera Capital","domain":"panteracapital.com","industry":"Venture Capital"},
    {"name":"Polychain Capital","domain":"polychain.capital","industry":"Venture Capital"},
    {"name":"Dragonfly Capital","domain":"dragonflycap.com","industry":"Venture Capital"},
    {"name":"General Atlantic Ventures","domain":"generalatlantic.com","industry":"Venture Capital"},
    {"name":"L2 Ventures","domain":"l2v.com","industry":"Venture Capital"},
    {"name":"Bain Capital Ventures","domain":"baincapitalventures.com","industry":"Venture Capital"},
    {"name":"Goldman Sachs Growth","domain":"goldmansachs.com","industry":"Venture Capital"},
    {"name":"JPMorgan Growth Equity","domain":"jpmorgan.com","industry":"Venture Capital"},
    {"name":"Andreessen Horowitz","domain":"a16z.com","industry":"Venture Capital"},
    {"name":"Upfront Ventures","domain":"upfront.com","industry":"Venture Capital"},
    {"name":"Crosscut Ventures","domain":"crosscut.vc","industry":"Venture Capital"},
    {"name":"Double Down Interactive","domain":"doubledowninteractive.com","industry":"Venture Capital"},

    {"name":"BlackRock","domain":"blackrock.com","industry":"Asset Management"},
    {"name":"Vanguard","domain":"vanguard.com","industry":"Asset Management"},
    {"name":"Fidelity Investments","domain":"fidelity.com","industry":"Asset Management"},
    {"name":"State Street","domain":"statestreet.com","industry":"Asset Management"},
    {"name":"JP Morgan Asset Management","domain":"am.jpmorgan.com","industry":"Asset Management"},
    {"name":"Goldman Sachs Asset Management","domain":"gsam.com","industry":"Asset Management"},
    {"name":"PIMCO","domain":"pimco.com","industry":"Asset Management"},
    {"name":"T. Rowe Price","domain":"troweprice.com","industry":"Asset Management"},
    {"name":"Capital Group","domain":"capitalgroup.com","industry":"Asset Management"},
    {"name":"Wellington Management","domain":"wellington.com","industry":"Asset Management"},
    {"name":"Franklin Templeton","domain":"franklintempleton.com","industry":"Asset Management"},
    {"name":"Invesco","domain":"invesco.com","industry":"Asset Management"},
    {"name":"Northern Trust","domain":"northerntrust.com","industry":"Asset Management"},
    {"name":"Nuveen","domain":"nuveen.com","industry":"Asset Management"},
    {"name":"Putnam Investments","domain":"putnam.com","industry":"Asset Management"},
    {"name":"MFS Investment Management","domain":"mfs.com","industry":"Asset Management"},
    {"name":"Lord Abbett","domain":"lordabbett.com","industry":"Asset Management"},
    {"name":"Dodge & Cox","domain":"dodgeandcox.com","industry":"Asset Management"},
    {"name":"Calvert Research","domain":"calvert.com","industry":"Asset Management"},
    {"name":"Dimensional Fund Advisors","domain":"dimensional.com","industry":"Asset Management"},
    {"name":"William Blair Asset Management","domain":"williamblair.com","industry":"Asset Management"},
    {"name":"Baird Asset Management","domain":"rwbaird.com","industry":"Asset Management"},
    {"name":"Cohen & Steers","domain":"cohenandsteers.com","industry":"Asset Management"},
    {"name":"Lazard Asset Management","domain":"lazardassetmanagement.com","industry":"Asset Management"},
    {"name":"Neuberger Berman","domain":"nb.com","industry":"Asset Management"},
    {"name":"Legg Mason","domain":"leggmason.com","industry":"Asset Management"},
    {"name":"Western Asset","domain":"westernasset.com","industry":"Asset Management"},
    {"name":"Alliance Bernstein","domain":"alliancebernstein.com","industry":"Asset Management"},
    {"name":"Eaton Vance","domain":"eatonvance.com","industry":"Asset Management"},
    {"name":"Columbia Threadneedle","domain":"columbiathreadneedle.com","industry":"Asset Management"},
    {"name":"American Century Investments","domain":"americancentury.com","industry":"Asset Management"},
    {"name":"Hartford Funds","domain":"hartfordfunds.com","industry":"Asset Management"},
    {"name":"Principal Financial","domain":"principal.com","industry":"Asset Management"},
    {"name":"Nationwide Mutual","domain":"nationwide.com","industry":"Asset Management"},
    {"name":"Pacific Investment Management","domain":"pimco.com","industry":"Asset Management"},
    {"name":"GMO","domain":"gmo.com","industry":"Asset Management"},
    {"name":"Loomis Sayles","domain":"loomissayles.com","industry":"Asset Management"},
    {"name":"Manning & Napier","domain":"manning-napier.com","industry":"Asset Management"},
    {"name":"Artisan Partners","domain":"artisanpartners.com","industry":"Asset Management"},
    {"name":"Wasatch Global Investors","domain":"wasatchglobal.com","industry":"Asset Management"},
    {"name":"Brown Advisory","domain":"brownadvisory.com","industry":"Asset Management"},
    {"name":"Royce Investment Partners","domain":"roycefunds.com","industry":"Asset Management"},
    {"name":"Gabelli Funds","domain":"gabelli.com","industry":"Asset Management"},
    {"name":"Parnassus Investments","domain":"parnassus.com","industry":"Asset Management"},
    {"name":"Calamos Investments","domain":"calamos.com","industry":"Asset Management"},
    {"name":"Thornburg Investment Management","domain":"thornburg.com","industry":"Asset Management"},
    {"name":"Janus Henderson","domain":"janushenderson.com","industry":"Asset Management"},
    {"name":"Man Investments","domain":"maninvestments.com","industry":"Asset Management"},
    {"name":"Schroders","domain":"schroders.com","industry":"Asset Management"},
    {"name":"Baillie Gifford","domain":"bailliegifford.com","industry":"Asset Management"},
    {"name":"Rathbone Brothers","domain":"rathbones.com","industry":"Asset Management"},
    {"name":"Standard Life Aberdeen","domain":"standardlifeinvestments.com","industry":"Asset Management"},
    {"name":"Aviva Investors","domain":"avivainvestors.com","industry":"Asset Management"},
    {"name":"Legal & General Investment","domain":"lgim.com","industry":"Asset Management"},
    {"name":"M&G Investments","domain":"mandg.com","industry":"Asset Management"},
    {"name":"Hermes Investment Management","domain":"hermes-investment.com","industry":"Asset Management"},
    {"name":"APG Asset Management","domain":"apg.nl","industry":"Asset Management"},
    {"name":"PGGM","domain":"pggm.nl","industry":"Asset Management"},
    {"name":"Amundi","domain":"amundi.com","industry":"Asset Management"},
    {"name":"BNP Paribas Asset Management","domain":"bnpparibas-am.com","industry":"Asset Management"},
    {"name":"Natixis Investment Managers","domain":"natixis-im.com","industry":"Asset Management"},
    {"name":"Credit Agricole AM","domain":"credit-agricole-am.com","industry":"Asset Management"},
    {"name":"AXA Investment Managers","domain":"axa-im.com","industry":"Asset Management"},
    {"name":"DWS Group","domain":"dws.com","industry":"Asset Management"},
    {"name":"Union Investment","domain":"union-investment.com","industry":"Asset Management"},
    {"name":"Deka Investments","domain":"deka.de","industry":"Asset Management"},
    {"name":"Allianz Global Investors","domain":"allianzgi.com","industry":"Asset Management"},
    {"name":"Nikko Asset Management","domain":"nikkoam.com","industry":"Asset Management"},
    {"name":"Nomura Asset Management","domain":"nomura-am.co.jp","industry":"Asset Management"},
    {"name":"GIC","domain":"gic.com.sg","industry":"Asset Management"},
    {"name":"Temasek","domain":"temasek.com.sg","industry":"Asset Management"},
    {"name":"ADIA","domain":"adia.ae","industry":"Asset Management"},
    {"name":"Mubadala","domain":"mubadala.com","industry":"Asset Management"},
    {"name":"Public Investment Fund","domain":"pif.gov.sa","industry":"Asset Management"},
    {"name":"Norway Government Pension Fund","domain":"nbim.no","industry":"Asset Management"},
    {"name":"CalPERS","domain":"calpers.ca.gov","industry":"Asset Management"},
    {"name":"CalSTRS","domain":"calstrs.com","industry":"Asset Management"},
    {"name":"CDPQ","domain":"cdpq.com","industry":"Asset Management"},
    {"name":"CPP Investments","domain":"cppib.com","industry":"Asset Management"},
    {"name":"Ontario Teachers Pension","domain":"otpp.com","industry":"Asset Management"},

    {"name":"CBRE","domain":"cbre.com","industry":"Real Estate"},
    {"name":"JLL","domain":"jll.com","industry":"Real Estate"},
    {"name":"Cushman & Wakefield","domain":"cushmanwakefield.com","industry":"Real Estate"},
    {"name":"Colliers International","domain":"colliers.com","industry":"Real Estate"},
    {"name":"Newmark","domain":"nmrk.com","industry":"Real Estate"},
    {"name":"Marcus & Millichap","domain":"marcusmillichap.com","industry":"Real Estate"},
    {"name":"Prologis","domain":"prologis.com","industry":"Real Estate"},
    {"name":"Simon Property Group","domain":"simon.com","industry":"Real Estate"},
    {"name":"Brookfield Asset Management","domain":"brookfield.com","industry":"Real Estate"},
    {"name":"Equity Residential","domain":"equityapartments.com","industry":"Real Estate"},
    {"name":"AvalonBay Communities","domain":"avalonbay.com","industry":"Real Estate"},
    {"name":"Boston Properties","domain":"bostonproperties.com","industry":"Real Estate"},
    {"name":"Vornado Realty Trust","domain":"vno.com","industry":"Real Estate"},
    {"name":"SL Green Realty","domain":"slgreen.com","industry":"Real Estate"},
    {"name":"Mack-Cali Realty","domain":"mack-cali.com","industry":"Real Estate"},
    {"name":"Essex Property Trust","domain":"essexapartmenthomes.com","industry":"Real Estate"},
    {"name":"UDR","domain":"udr.com","industry":"Real Estate"},
    {"name":"Camden Property Trust","domain":"camdenliving.com","industry":"Real Estate"},
    {"name":"Mid-America Apartment","domain":"maac.com","industry":"Real Estate"},
    {"name":"Invitation Homes","domain":"invitationhomes.com","industry":"Real Estate"},
    {"name":"American Tower","domain":"americantower.com","industry":"Real Estate"},
    {"name":"Crown Castle","domain":"crowncastle.com","industry":"Real Estate"},
    {"name":"SBA Communications","domain":"sbasite.com","industry":"Real Estate"},
    {"name":"Digital Realty","domain":"digitalrealty.com","industry":"Real Estate"},
    {"name":"Equinix","domain":"equinix.com","industry":"Real Estate"},
    {"name":"Iron Mountain","domain":"ironmountain.com","industry":"Real Estate"},
    {"name":"Ventas","domain":"ventasreit.com","industry":"Real Estate"},
    {"name":"Welltower","domain":"welltower.com","industry":"Real Estate"},
    {"name":"Healthpeak Properties","domain":"healthpeak.com","industry":"Real Estate"},
    {"name":"Medical Properties Trust","domain":"medicalpropertiestrust.com","industry":"Real Estate"},
    {"name":"Realty Income","domain":"realtyincome.com","industry":"Real Estate"},
    {"name":"National Retail Properties","domain":"nnnreit.com","industry":"Real Estate"},
    {"name":"W.P. Carey","domain":"wpcarey.com","industry":"Real Estate"},
    {"name":"STORE Capital","domain":"storecapital.com","industry":"Real Estate"},
    {"name":"EPR Properties","domain":"eprkc.com","industry":"Real Estate"},
    {"name":"Weyerhaeuser","domain":"weyerhaeuser.com","industry":"Real Estate"},
    {"name":"Rayonier","domain":"rayonier.com","industry":"Real Estate"},
    {"name":"PotlatchDeltic","domain":"potlatchdeltic.com","industry":"Real Estate"},
    {"name":"Host Hotels","domain":"hosthotels.com","industry":"Real Estate"},
    {"name":"Park Hotels & Resorts","domain":"pkhotelsandresorts.com","industry":"Real Estate"},
    {"name":"RLJ Lodging Trust","domain":"rljlodgingtrust.com","industry":"Real Estate"},
    {"name":"Kimco Realty","domain":"kimcorealty.com","industry":"Real Estate"},
    {"name":"Regency Centers","domain":"regencycenters.com","industry":"Real Estate"},
    {"name":"Federal Realty Investment Trust","domain":"federalrealty.com","industry":"Real Estate"},
    {"name":"Acadia Realty Trust","domain":"acadiarealty.com","industry":"Real Estate"},
    {"name":"Kite Realty Group","domain":"kiterealty.com","industry":"Real Estate"},
    {"name":"Inland Real Estate","domain":"inlandgroup.com","industry":"Real Estate"},
    {"name":"Thor Equities","domain":"thorequities.com","industry":"Real Estate"},
    {"name":"Related Companies","domain":"related.com","industry":"Real Estate"},
    {"name":"Tishman Speyer","domain":"tishmanspeyer.com","industry":"Real Estate"},
    {"name":"Hines","domain":"hines.com","industry":"Real Estate"},
    {"name":"Trammell Crow Company","domain":"trammellcrow.com","industry":"Real Estate"},
    {"name":"Lincoln Property Company","domain":"lincolnapts.com","industry":"Real Estate"},
    {"name":"Greystar","domain":"greystar.com","industry":"Real Estate"},
    {"name":"Aimco","domain":"aimco.com","industry":"Real Estate"},
    {"name":"National Western Financial","domain":"nwfinancial.com","industry":"Real Estate"},
    {"name":"Meredith Corporation RE","domain":"meredithapts.com","industry":"Real Estate"},
    {"name":"Lendlease","domain":"lendlease.com","industry":"Real Estate"},
    {"name":"Grosvenor Group","domain":"grosvenor.com","industry":"Real Estate"},
    {"name":"Savills","domain":"savills.com","industry":"Real Estate"},
    {"name":"Knight Frank","domain":"knightfrank.com","industry":"Real Estate"},
    {"name":"BNP Paribas Real Estate","domain":"realestate.bnpparibas.com","industry":"Real Estate"},
    {"name":"Patrizia","domain":"patrizia.ag","industry":"Real Estate"},
    {"name":"AEW Capital Management","domain":"aew.com","industry":"Real Estate"},
    {"name":"LaSalle Investment Management","domain":"lasalle.com","industry":"Real Estate"},
    {"name":"Nuveen Real Estate","domain":"nuveen.com","industry":"Real Estate"},
    {"name":"PGIM Real Estate","domain":"pgimrealestate.com","industry":"Real Estate"},
    {"name":"Principal Real Estate","domain":"principalrem.com","industry":"Real Estate"},
    {"name":"MetLife Investment Management","domain":"metlife.com","industry":"Real Estate"},
    {"name":"Oxford Properties","domain":"oxfordproperties.com","industry":"Real Estate"},
    {"name":"GLP","domain":"glp.com","industry":"Real Estate"},
    {"name":"ESR Group","domain":"esr.com","industry":"Real Estate"},
    {"name":"Link REIT","domain":"linkreit.com","industry":"Real Estate"},
    {"name":"Keppel Land","domain":"kepcorp.com","industry":"Real Estate"},
    {"name":"CapitaLand","domain":"capitaland.com","industry":"Real Estate"},
    {"name":"Mapletree Investments","domain":"mapletree.com.sg","industry":"Real Estate"},
    {"name":"Sun Hung Kai Properties","domain":"shkp.com","industry":"Real Estate"},

    {"name":"Lockheed Martin","domain":"lockheedmartin.com","industry":"Engineering & Defense"},
    {"name":"Boeing","domain":"boeing.com","industry":"Engineering & Defense"},
    {"name":"Raytheon Technologies","domain":"rtx.com","industry":"Engineering & Defense"},
    {"name":"Northrop Grumman","domain":"northropgrumman.com","industry":"Engineering & Defense"},
    {"name":"General Dynamics","domain":"gd.com","industry":"Engineering & Defense"},
    {"name":"BAE Systems","domain":"baesystems.com","industry":"Engineering & Defense"},
    {"name":"L3Harris Technologies","domain":"l3harris.com","industry":"Engineering & Defense"},
    {"name":"Leidos","domain":"leidos.com","industry":"Engineering & Defense"},
    {"name":"SAIC","domain":"saic.com","industry":"Engineering & Defense"},
    {"name":"Booz Allen Hamilton","domain":"boozallen.com","industry":"Engineering & Defense"},
    {"name":"MITRE Corporation","domain":"mitre.org","industry":"Engineering & Defense"},
    {"name":"Textron","domain":"textron.com","industry":"Engineering & Defense"},
    {"name":"Honeywell Defense","domain":"honeywell.com","industry":"Engineering & Defense"},
    {"name":"Thales Group","domain":"thalesgroup.com","industry":"Engineering & Defense"},
    {"name":"Leonardo","domain":"leonardocompany.com","industry":"Engineering & Defense"},
    {"name":"Airbus","domain":"airbus.com","industry":"Engineering & Defense"},
    {"name":"Rheinmetall","domain":"rheinmetall.com","industry":"Engineering & Defense"},
    {"name":"MBDA","domain":"mbda-systems.com","industry":"Engineering & Defense"},
    {"name":"Saab","domain":"saab.com","industry":"Engineering & Defense"},
    {"name":"Dassault Aviation","domain":"dassault-aviation.com","industry":"Engineering & Defense"},
    {"name":"General Electric Aviation","domain":"ge.com","industry":"Engineering & Defense"},
    {"name":"Rolls-Royce","domain":"rolls-royce.com","industry":"Engineering & Defense"},
    {"name":"Pratt & Whitney","domain":"prattwhitney.com","industry":"Engineering & Defense"},
    {"name":"Safran","domain":"safran-group.com","industry":"Engineering & Defense"},
    {"name":"TransDigm Group","domain":"transdigm.com","industry":"Engineering & Defense"},
    {"name":"DRS Technologies","domain":"drs.com","industry":"Engineering & Defense"},
    {"name":"Parsons Corporation","domain":"parsons.com","industry":"Engineering & Defense"},
    {"name":"Jacobs Engineering","domain":"jacobs.com","industry":"Engineering & Defense"},
    {"name":"AECOM","domain":"aecom.com","industry":"Engineering & Defense"},
    {"name":"KBR","domain":"kbr.com","industry":"Engineering & Defense"},
    {"name":"Fluor Corporation","domain":"fluor.com","industry":"Engineering & Defense"},
    {"name":"Bechtel","domain":"bechtel.com","industry":"Engineering & Defense"},
    {"name":"Worley","domain":"worley.com","industry":"Engineering & Defense"},
    {"name":"Wood Group","domain":"woodgroup.com","industry":"Engineering & Defense"},
    {"name":"SNC-Lavalin","domain":"snclavalin.com","industry":"Engineering & Defense"},
    {"name":"WSP Global","domain":"wsp.com","industry":"Engineering & Defense"},
    {"name":"Stantec","domain":"stantec.com","industry":"Engineering & Defense"},
    {"name":"Arcadis","domain":"arcadis.com","industry":"Engineering & Defense"},
    {"name":"Arup","domain":"arup.com","industry":"Engineering & Defense"},
    {"name":"HNTB","domain":"hntb.com","industry":"Engineering & Defense"},
    {"name":"CH2M Hill","domain":"ch2m.com","industry":"Engineering & Defense"},
    {"name":"Tetra Tech","domain":"tetratech.com","industry":"Engineering & Defense"},
    {"name":"CDM Smith","domain":"cdmsmith.com","industry":"Engineering & Defense"},
    {"name":"Golder Associates","domain":"golder.com","industry":"Engineering & Defense"},
    {"name":"Mott MacDonald","domain":"mottmac.com","industry":"Engineering & Defense"},
    {"name":"Halliburton","domain":"halliburton.com","industry":"Engineering & Defense"},
    {"name":"Schlumberger (SLB)","domain":"slb.com","industry":"Engineering & Defense"},
    {"name":"Baker Hughes","domain":"bakerhughes.com","industry":"Engineering & Defense"},
    {"name":"TechnipFMC","domain":"technipfmc.com","industry":"Engineering & Defense"},
    {"name":"McDermott International","domain":"mcdermott.com","industry":"Engineering & Defense"},
    {"name":"Perini Corporation","domain":"tutor-perini.com","industry":"Engineering & Defense"},
    {"name":"Kiewit","domain":"kiewit.com","industry":"Engineering & Defense"},
    {"name":"Turner Construction","domain":"turnerconstruction.com","industry":"Engineering & Defense"},
    {"name":"Skanska","domain":"skanska.com","industry":"Engineering & Defense"},
    {"name":"Vinci Construction","domain":"vinci.com","industry":"Engineering & Defense"},
    {"name":"Bouygues Construction","domain":"bouygues-construction.com","industry":"Engineering & Defense"},
    {"name":"ACS Group","domain":"grupoacs.com","industry":"Engineering & Defense"},
    {"name":"Ferrovial","domain":"ferrovial.com","industry":"Engineering & Defense"},
    {"name":"Granite Construction","domain":"graniteconstruction.com","industry":"Engineering & Defense"},
    {"name":"DXC Technology","domain":"dxc.com","industry":"Engineering & Defense"},
    {"name":"ManTech International","domain":"mantech.com","industry":"Engineering & Defense"},
    {"name":"Engility","domain":"engility.com","industry":"Engineering & Defense"},
    {"name":"CACI International","domain":"caci.com","industry":"Engineering & Defense"},
    {"name":"Cubic Corporation","domain":"cubic.com","industry":"Engineering & Defense"},
    {"name":"FLIR Systems","domain":"flir.com","industry":"Engineering & Defense"},
    {"name":"Curtiss-Wright","domain":"curtisswright.com","industry":"Engineering & Defense"},
    {"name":"Mercury Systems","domain":"mrcy.com","industry":"Engineering & Defense"},
    {"name":"Kratos Defense","domain":"kratosdefense.com","industry":"Engineering & Defense"},
    {"name":"OSI Systems","domain":"osi-systems.com","industry":"Engineering & Defense"},
    {"name":"Elbit Systems","domain":"elbitsystems.com","industry":"Engineering & Defense"},
    {"name":"Rafael Advanced Defense","domain":"rafael.co.il","industry":"Engineering & Defense"},
    {"name":"IAI","domain":"iai.co.il","industry":"Engineering & Defense"},
    {"name":"Kongsberg Gruppen","domain":"kongsberg.com","industry":"Engineering & Defense"},
    {"name":"Patria","domain":"patriagroup.com","industry":"Engineering & Defense"},
    {"name":"Indra Sistemas","domain":"indracompany.com","industry":"Engineering & Defense"},
    {"name":"KNDS","domain":"knds.com","industry":"Engineering & Defense"},
    {"name":"ST Engineering","domain":"stengg.com","industry":"Engineering & Defense"},

    {"name":"MIT","domain":"mit.edu","industry":"College Engineering Programs"},
    {"name":"Stanford University","domain":"stanford.edu","industry":"College Engineering Programs"},
    {"name":"UC Berkeley","domain":"berkeley.edu","industry":"College Engineering Programs"},
    {"name":"Caltech","domain":"caltech.edu","industry":"College Engineering Programs"},
    {"name":"Georgia Tech","domain":"gatech.edu","industry":"College Engineering Programs"},
    {"name":"University of Michigan","domain":"umich.edu","industry":"College Engineering Programs"},
    {"name":"UIUC","domain":"illinois.edu","industry":"College Engineering Programs"},
    {"name":"Carnegie Mellon","domain":"cmu.edu","industry":"College Engineering Programs"},
    {"name":"Purdue University","domain":"purdue.edu","industry":"College Engineering Programs"},
    {"name":"UCLA","domain":"ucla.edu","industry":"College Engineering Programs"},
    {"name":"UT Austin","domain":"utexas.edu","industry":"College Engineering Programs"},
    {"name":"Cornell University","domain":"cornell.edu","industry":"College Engineering Programs"},
    {"name":"Princeton University","domain":"princeton.edu","industry":"College Engineering Programs"},
    {"name":"Duke University","domain":"duke.edu","industry":"College Engineering Programs"},
    {"name":"Johns Hopkins","domain":"jhu.edu","industry":"College Engineering Programs"},
    {"name":"Virginia Tech","domain":"vt.edu","industry":"College Engineering Programs"},
    {"name":"Ohio State University","domain":"osu.edu","industry":"College Engineering Programs"},
    {"name":"Penn State","domain":"psu.edu","industry":"College Engineering Programs"},
    {"name":"Texas A&M","domain":"tamu.edu","industry":"College Engineering Programs"},
    {"name":"Northwestern University","domain":"northwestern.edu","industry":"College Engineering Programs"},
    {"name":"USC","domain":"usc.edu","industry":"College Engineering Programs"},
    {"name":"Rice University","domain":"rice.edu","industry":"College Engineering Programs"},
    {"name":"UC San Diego","domain":"ucsd.edu","industry":"College Engineering Programs"},
    {"name":"University of Washington","domain":"uw.edu","industry":"College Engineering Programs"},
    {"name":"University of Wisconsin","domain":"wisc.edu","industry":"College Engineering Programs"},
    {"name":"University of Minnesota","domain":"umn.edu","industry":"College Engineering Programs"},
    {"name":"NC State","domain":"ncsu.edu","industry":"College Engineering Programs"},
    {"name":"Northeastern University","domain":"northeastern.edu","industry":"College Engineering Programs"},
    {"name":"Harvey Mudd College","domain":"hmc.edu","industry":"College Engineering Programs"},
    {"name":"WPI","domain":"wpi.edu","industry":"College Engineering Programs"},
    {"name":"Case Western Reserve","domain":"case.edu","industry":"College Engineering Programs"},
    {"name":"Drexel University","domain":"drexel.edu","industry":"College Engineering Programs"},
    {"name":"Lehigh University","domain":"lehigh.edu","industry":"College Engineering Programs"},
    {"name":"Rensselaer Polytechnic (RPI)","domain":"rpi.edu","industry":"College Engineering Programs"},
    {"name":"Stevens Institute of Technology","domain":"stevens.edu","industry":"College Engineering Programs"},
    {"name":"Colorado School of Mines","domain":"mines.edu","industry":"College Engineering Programs"},
    {"name":"Michigan Tech","domain":"mtu.edu","industry":"College Engineering Programs"},
    {"name":"Iowa State University","domain":"iastate.edu","industry":"College Engineering Programs"},
    {"name":"Arizona State University","domain":"asu.edu","industry":"College Engineering Programs"},
    {"name":"University of Maryland","domain":"umd.edu","industry":"College Engineering Programs"},
    {"name":"Rutgers University","domain":"rutgers.edu","industry":"College Engineering Programs"},
    {"name":"Stony Brook University","domain":"stonybrook.edu","industry":"College Engineering Programs"},
    {"name":"University at Buffalo","domain":"buffalo.edu","industry":"College Engineering Programs"},
    {"name":"University of Florida","domain":"ufl.edu","industry":"College Engineering Programs"},
    {"name":"University of Virginia","domain":"virginia.edu","industry":"College Engineering Programs"},
    {"name":"Vanderbilt University","domain":"vanderbilt.edu","industry":"College Engineering Programs"},
    {"name":"Tufts University","domain":"tufts.edu","industry":"College Engineering Programs"},
    {"name":"Boston University","domain":"bu.edu","industry":"College Engineering Programs"},
    {"name":"Santa Clara University","domain":"scu.edu","industry":"College Engineering Programs"},
    {"name":"Notre Dame","domain":"nd.edu","industry":"College Engineering Programs"},
    {"name":"Clemson University","domain":"clemson.edu","industry":"College Engineering Programs"},
    {"name":"University of Tennessee","domain":"utk.edu","industry":"College Engineering Programs"},
    {"name":"Auburn University","domain":"auburn.edu","industry":"College Engineering Programs"},
    {"name":"University of Alabama","domain":"ua.edu","industry":"College Engineering Programs"},
    {"name":"Mississippi State University","domain":"msstate.edu","industry":"College Engineering Programs"},
    {"name":"University of Kentucky","domain":"uky.edu","industry":"College Engineering Programs"},
    {"name":"University of Colorado","domain":"colorado.edu","industry":"College Engineering Programs"},
    {"name":"Oregon State University","domain":"oregonstate.edu","industry":"College Engineering Programs"},
    {"name":"Washington State University","domain":"wsu.edu","industry":"College Engineering Programs"},
    {"name":"University of Utah","domain":"utah.edu","industry":"College Engineering Programs"},
    {"name":"BYU","domain":"byu.edu","industry":"College Engineering Programs"},
    {"name":"University of Nebraska","domain":"unl.edu","industry":"College Engineering Programs"},
    {"name":"Kansas State University","domain":"k-state.edu","industry":"College Engineering Programs"},
    {"name":"University of Kansas","domain":"ku.edu","industry":"College Engineering Programs"},
    {"name":"Villanova University","domain":"villanova.edu","industry":"College Engineering Programs"},
    {"name":"Marquette University","domain":"marquette.edu","industry":"College Engineering Programs"},
    {"name":"Naval Academy (USNA)","domain":"usna.edu","industry":"College Engineering Programs"},
    {"name":"West Point","domain":"westpoint.edu","industry":"College Engineering Programs"},
    {"name":"Air Force Academy","domain":"usafa.edu","industry":"College Engineering Programs"},
    {"name":"University of Waterloo","domain":"uwaterloo.ca","industry":"College Engineering Programs"},
    {"name":"University of Toronto","domain":"utoronto.ca","industry":"College Engineering Programs"},
    {"name":"McGill University","domain":"mcgill.ca","industry":"College Engineering Programs"},
    {"name":"Imperial College London","domain":"imperial.ac.uk","industry":"College Engineering Programs"},
    {"name":"ETH Zurich","domain":"ethz.ch","industry":"College Engineering Programs"},
    {"name":"TU Munich","domain":"tum.de","industry":"College Engineering Programs"},
    {"name":"TU Delft","domain":"tudelft.nl","industry":"College Engineering Programs"},
    {"name":"EPFL","domain":"epfl.ch","industry":"College Engineering Programs"},
    {"name":"National University of Singapore","domain":"nus.edu.sg","industry":"College Engineering Programs"},
    {"name":"UC Davis","domain":"ucdavis.edu","industry":"College Engineering Programs"},
    {"name":"UC Santa Barbara","domain":"ucsb.edu","industry":"College Engineering Programs"},
    {"name":"University of Pittsburgh","domain":"pitt.edu","industry":"College Engineering Programs"},
    {"name":"Temple University","domain":"temple.edu","industry":"College Engineering Programs"},

    {"name":"Harvard Business School","domain":"hbs.edu","industry":"College Business Programs"},
    {"name":"Wharton School","domain":"wharton.upenn.edu","industry":"College Business Programs"},
    {"name":"Stanford GSB","domain":"gsb.stanford.edu","industry":"College Business Programs"},
    {"name":"Booth School of Business","domain":"chicagobooth.edu","industry":"College Business Programs"},
    {"name":"Kellogg School of Management","domain":"kellogg.northwestern.edu","industry":"College Business Programs"},
    {"name":"MIT Sloan","domain":"mitsloan.mit.edu","industry":"College Business Programs"},
    {"name":"Haas School of Business","domain":"haas.berkeley.edu","industry":"College Business Programs"},
    {"name":"Tuck School of Business","domain":"tuck.dartmouth.edu","industry":"College Business Programs"},
    {"name":"Stern School of Business","domain":"stern.nyu.edu","industry":"College Business Programs"},
    {"name":"Darden School of Business","domain":"darden.virginia.edu","industry":"College Business Programs"},
    {"name":"Ross School of Business","domain":"bus.umich.edu","industry":"College Business Programs"},
    {"name":"Fuqua School of Business","domain":"fuqua.duke.edu","industry":"College Business Programs"},
    {"name":"Yale School of Management","domain":"som.yale.edu","industry":"College Business Programs"},
    {"name":"Johnson School of Management","domain":"johnson.cornell.edu","industry":"College Business Programs"},
    {"name":"McCombs School of Business","domain":"mccombs.utexas.edu","industry":"College Business Programs"},
    {"name":"Marshall School of Business","domain":"marshall.usc.edu","industry":"College Business Programs"},
    {"name":"Anderson School of Management","domain":"anderson.ucla.edu","industry":"College Business Programs"},
    {"name":"Kenan-Flagler Business School","domain":"kenan-flagler.unc.edu","industry":"College Business Programs"},
    {"name":"Tepper School of Business","domain":"tepper.cmu.edu","industry":"College Business Programs"},
    {"name":"Mendoza College of Business","domain":"mendoza.nd.edu","industry":"College Business Programs"},
    {"name":"Fisher College of Business","domain":"fisher.osu.edu","industry":"College Business Programs"},
    {"name":"Kelley School of Business","domain":"kelley.iu.edu","industry":"College Business Programs"},
    {"name":"Olin Business School","domain":"olin.wustl.edu","industry":"College Business Programs"},
    {"name":"Simon Business School","domain":"simon.rochester.edu","industry":"College Business Programs"},
    {"name":"Carey Business School","domain":"carey.jhu.edu","industry":"College Business Programs"},
    {"name":"Questrom School of Business","domain":"questrom.bu.edu","industry":"College Business Programs"},
    {"name":"Cox School of Business","domain":"cox.smu.edu","industry":"College Business Programs"},
    {"name":"Jones Graduate School of Business","domain":"business.rice.edu","industry":"College Business Programs"},
    {"name":"Smeal College of Business","domain":"smeal.psu.edu","industry":"College Business Programs"},
    {"name":"Robert H. Smith School","domain":"rhsmith.umd.edu","industry":"College Business Programs"},
    {"name":"Foster School of Business","domain":"foster.uw.edu","industry":"College Business Programs"},
    {"name":"Lundquist College of Business","domain":"lundquist.uoregon.edu","industry":"College Business Programs"},
    {"name":"Eller College of Management","domain":"eller.arizona.edu","industry":"College Business Programs"},
    {"name":"W.P. Carey School of Business","domain":"wpcarey.asu.edu","industry":"College Business Programs"},
    {"name":"Marriott School of Business","domain":"marriottschool.byu.edu","industry":"College Business Programs"},
    {"name":"Eccles School of Business","domain":"eccles.utah.edu","industry":"College Business Programs"},
    {"name":"Leeds School of Business","domain":"colorado.edu","industry":"College Business Programs"},
    {"name":"Daniels College of Business","domain":"daniels.du.edu","industry":"College Business Programs"},
    {"name":"Tippie College of Business","domain":"tippie.uiowa.edu","industry":"College Business Programs"},
    {"name":"Carlson School of Management","domain":"carlsonschool.umn.edu","industry":"College Business Programs"},
    {"name":"Pamplin College of Business","domain":"pamplin.vt.edu","industry":"College Business Programs"},
    {"name":"Broad College of Business","domain":"broad.msu.edu","industry":"College Business Programs"},
    {"name":"Mays Business School","domain":"mays.tamu.edu","industry":"College Business Programs"},
    {"name":"Neeley School of Business","domain":"neeley.tcu.edu","industry":"College Business Programs"},
    {"name":"Moore School of Business","domain":"moore.sc.edu","industry":"College Business Programs"},
    {"name":"Warrington College of Business","domain":"warrington.ufl.edu","industry":"College Business Programs"},
    {"name":"INSEAD","domain":"insead.edu","industry":"College Business Programs"},
    {"name":"London Business School","domain":"lbs.ac.uk","industry":"College Business Programs"},
    {"name":"London School of Economics","domain":"lse.ac.uk","industry":"College Business Programs"},
    {"name":"Oxford Said Business School","domain":"sbs.ox.ac.uk","industry":"College Business Programs"},
    {"name":"Cambridge Judge Business School","domain":"jbs.cam.ac.uk","industry":"College Business Programs"},
    {"name":"IE Business School","domain":"ie.edu","industry":"College Business Programs"},
    {"name":"ESADE Business School","domain":"esade.edu","industry":"College Business Programs"},
    {"name":"HEC Paris","domain":"hec.edu","industry":"College Business Programs"},
    {"name":"IESE Business School","domain":"iese.edu","industry":"College Business Programs"},
    {"name":"Bocconi University","domain":"unibocconi.it","industry":"College Business Programs"},
    {"name":"WHU Otto Beisheim School","domain":"whu.edu","industry":"College Business Programs"},
    {"name":"ESMT Berlin","domain":"esmt.org","industry":"College Business Programs"},
    {"name":"IMD Business School","domain":"imd.org","industry":"College Business Programs"},
    {"name":"University of St. Gallen","domain":"unisg.ch","industry":"College Business Programs"},
    {"name":"Rotterdam School of Management","domain":"rsm.nl","industry":"College Business Programs"},
    {"name":"Copenhagen Business School","domain":"cbs.dk","industry":"College Business Programs"},
    {"name":"BI Norwegian Business School","domain":"bi.no","industry":"College Business Programs"},
    {"name":"NUS Business School","domain":"bschool.nus.edu.sg","industry":"College Business Programs"},
    {"name":"HKUST Business School","domain":"bm.ust.hk","industry":"College Business Programs"},
    {"name":"CEIBS","domain":"ceibs.edu","industry":"College Business Programs"},
    {"name":"Indian School of Business","domain":"isb.edu","industry":"College Business Programs"},
    {"name":"IIM Ahmedabad","domain":"iima.ac.in","industry":"College Business Programs"},
    {"name":"IIM Bangalore","domain":"iimb.ac.in","industry":"College Business Programs"},
    {"name":"Rotman School of Management","domain":"rotman.utoronto.ca","industry":"College Business Programs"},
    {"name":"Ivey Business School","domain":"ivey.uwo.ca","industry":"College Business Programs"},
    {"name":"Schulich School of Business","domain":"schulich.yorku.ca","industry":"College Business Programs"},
    {"name":"Smith School of Business","domain":"smith.queensu.ca","industry":"College Business Programs"},
    {"name":"Sauder School of Business","domain":"sauder.ubc.ca","industry":"College Business Programs"},
    {"name":"Haskayne School of Business","domain":"haskayne.ucalgary.ca","industry":"College Business Programs"},
    {"name":"DeGroote School of Business","domain":"degroote.mcmaster.ca","industry":"College Business Programs"},
    {"name":"Rawls College of Business","domain":"rawlsbusiness.ttu.edu","industry":"College Business Programs"},
    {"name":"Hankamer School of Business","domain":"hankamer.baylor.edu","industry":"College Business Programs"},
    {"name":"LeBow College of Business","domain":"lebow.drexel.edu","industry":"College Business Programs"},
    {"name":"Freeman School of Business","domain":"freeman.tulane.edu","industry":"College Business Programs"},
    {"name":"Kogod School of Business","domain":"kogod.american.edu","industry":"College Business Programs"},
    {"name":"Mason School of Business","domain":"mason.wm.edu","industry":"College Business Programs"},

    {"name":"Accenture","domain":"accenture.com","industry":"Technology Consulting"},
    {"name":"IBM Global Services","domain":"ibm.com","industry":"Technology Consulting"},
    {"name":"Deloitte Technology","domain":"deloitte.com","industry":"Technology Consulting"},
    {"name":"Capgemini","domain":"capgemini.com","industry":"Technology Consulting"},
    {"name":"Cognizant","domain":"cognizant.com","industry":"Technology Consulting"},
    {"name":"Infosys","domain":"infosys.com","industry":"Technology Consulting"},
    {"name":"Wipro","domain":"wipro.com","industry":"Technology Consulting"},
    {"name":"TCS","domain":"tcs.com","industry":"Technology Consulting"},
    {"name":"HCL Technologies","domain":"hcltech.com","industry":"Technology Consulting"},
    {"name":"DXC Technology","domain":"dxc.com","industry":"Technology Consulting"},
    {"name":"Unisys","domain":"unisys.com","industry":"Technology Consulting"},
    {"name":"CGI Group","domain":"cgi.com","industry":"Technology Consulting"},
    {"name":"Atos","domain":"atos.net","industry":"Technology Consulting"},
    {"name":"Sopra Steria","domain":"soprasteria.com","industry":"Technology Consulting"},
    {"name":"Fujitsu","domain":"fujitsu.com","industry":"Technology Consulting"},
    {"name":"NTT Data","domain":"nttdata.com","industry":"Technology Consulting"},
    {"name":"Mphasis","domain":"mphasis.com","industry":"Technology Consulting"},
    {"name":"Tech Mahindra","domain":"techmahindra.com","industry":"Technology Consulting"},
    {"name":"Hexaware Technologies","domain":"hexaware.com","industry":"Technology Consulting"},
    {"name":"LTIMindtree","domain":"ltimindtree.com","industry":"Technology Consulting"},
    {"name":"Persistent Systems","domain":"persistent.com","industry":"Technology Consulting"},
    {"name":"NIIT Technologies","domain":"niit-tech.com","industry":"Technology Consulting"},
    {"name":"Mastech Digital","domain":"mastech.com","industry":"Technology Consulting"},
    {"name":"Syntel","domain":"syntelinc.com","industry":"Technology Consulting"},
    {"name":"iGate","domain":"igate.com","industry":"Technology Consulting"},
    {"name":"Zensar Technologies","domain":"zensar.com","industry":"Technology Consulting"},
    {"name":"Kyndryl","domain":"kyndryl.com","industry":"Technology Consulting"},
    {"name":"Stefanini Group","domain":"stefanini.com","industry":"Technology Consulting"},
    {"name":"UST Global","domain":"ust.com","industry":"Technology Consulting"},
    {"name":"EPAM Systems","domain":"epam.com","industry":"Technology Consulting"},
    {"name":"Luxoft","domain":"luxoft.com","industry":"Technology Consulting"},
    {"name":"Thoughtworks","domain":"thoughtworks.com","industry":"Technology Consulting"},
    {"name":"Slalom","domain":"slalom.com","industry":"Technology Consulting"},
    {"name":"West Monroe","domain":"westmonroe.com","industry":"Technology Consulting"},
    {"name":"Publicis Sapient","domain":"publicissapient.com","industry":"Technology Consulting"},
    {"name":"Pivotal (now VMware Tanzu)","domain":"pivotal.io","industry":"Technology Consulting"},
    {"name":"Credera","domain":"credera.com","industry":"Technology Consulting"},
    {"name":"Kin + Carta","domain":"kinandcarta.com","industry":"Technology Consulting"},
    {"name":"10Pearls","domain":"10pearls.com","industry":"Technology Consulting"},
    {"name":"Nagarro","domain":"nagarro.com","industry":"Technology Consulting"},
    {"name":"Devoteam","domain":"devoteam.com","industry":"Technology Consulting"},
    {"name":"Valtech","domain":"valtech.com","industry":"Technology Consulting"},
    {"name":"Merkle","domain":"merkleinc.com","industry":"Technology Consulting"},
    {"name":"Sapient Consulting","domain":"sapient.com","industry":"Technology Consulting"},
    {"name":"Infosys BPM","domain":"infosysbpm.com","industry":"Technology Consulting"},
    {"name":"Genpact","domain":"genpact.com","industry":"Technology Consulting"},
    {"name":"EXL Service","domain":"exlservice.com","industry":"Technology Consulting"},
    {"name":"WNS","domain":"wns.com","industry":"Technology Consulting"},
    {"name":"Conduent","domain":"conduent.com","industry":"Technology Consulting"},
    {"name":"Concentrix","domain":"concentrix.com","industry":"Technology Consulting"},
    {"name":"Teleperformance","domain":"teleperformance.com","industry":"Technology Consulting"},
    {"name":"ManpowerGroup Solutions","domain":"manpowergroup.com","industry":"Technology Consulting"},
    {"name":"Booz Allen Hamilton","domain":"boozallen.com","industry":"Technology Consulting"},
    {"name":"SAIC","domain":"saic.com","industry":"Technology Consulting"},
    {"name":"Leidos","domain":"leidos.com","industry":"Technology Consulting"},
    {"name":"MITRE","domain":"mitre.org","industry":"Technology Consulting"},
    {"name":"CACI International","domain":"caci.com","industry":"Technology Consulting"},
    {"name":"ManTech","domain":"mantech.com","industry":"Technology Consulting"},
    {"name":"Peraton","domain":"peraton.com","industry":"Technology Consulting"},
    {"name":"Engility","domain":"engility.com","industry":"Technology Consulting"},
    {"name":"Sungard AS","domain":"sungardas.com","industry":"Technology Consulting"},
    {"name":"Presidio","domain":"presidio.com","industry":"Technology Consulting"},
    {"name":"Forsythe Technology","domain":"forsythe.com","industry":"Technology Consulting"},
    {"name":"Sirius Computer Solutions","domain":"siriuscom.com","industry":"Technology Consulting"},
    {"name":"World Wide Technology","domain":"wwt.com","industry":"Technology Consulting"},
    {"name":"CDW","domain":"cdw.com","industry":"Technology Consulting"},
    {"name":"Insight Direct","domain":"insight.com","industry":"Technology Consulting"},
    {"name":"SHI International","domain":"shi.com","industry":"Technology Consulting"},
    {"name":"Guidepoint Global","domain":"guidepointglobal.com","industry":"Technology Consulting"},
    {"name":"Hitachi Vantara","domain":"hitachivantara.com","industry":"Technology Consulting"},
    {"name":"Tata Elxsi","domain":"tataelxsi.com","industry":"Technology Consulting"},
    {"name":"Coforge","domain":"coforge.com","industry":"Technology Consulting"},
    {"name":"Moog Inc","domain":"moog.com","industry":"Technology Consulting"},
    {"name":"Unison Consulting","domain":"unisonconsulting.com","industry":"Technology Consulting"},
    {"name":"Netcracker Technology","domain":"netcracker.com","industry":"Technology Consulting"},
    {"name":"SPR Consulting","domain":"sprconsulting.com","industry":"Technology Consulting"},
    {"name":"A.I. Solutions","domain":"ai-solutions.com","industry":"Technology Consulting"},
    {"name":"Perot Systems (now NTT Data)","domain":"nttdataservices.com","industry":"Technology Consulting"},
    {"name":"Harman International","domain":"harman.com","industry":"Technology Consulting"},
    {"name":"Infor","domain":"infor.com","industry":"Technology Consulting"}
  ]'::jsonb;

  FOR rec IN SELECT * FROM jsonb_array_elements(companies)
  LOOP
    INSERT INTO companies (name, domain, industry)
    VALUES (rec->>'name', rec->>'domain', rec->>'industry')
    ON CONFLICT (domain) DO NOTHING
    RETURNING id INTO cid;

    IF cid IS NULL THEN
      SELECT id INTO cid FROM companies
      WHERE domain = rec->>'domain' AND industry = rec->>'industry';
    END IF;

    IF cid IS NOT NULL THEN
      FOREACH scope IN ARRAY scopes LOOP
        FOREACH level IN ARRAY levels LOOP
          INSERT INTO ratings (company_id, industry_scope, voter_level, elo, wins, losses, total_votes)
          VALUES (cid, scope, level, 1200, 0, 0, 0)
          ON CONFLICT (company_id, industry_scope, voter_level) DO NOTHING;
        END LOOP;
      END LOOP;
    END IF;
  END LOOP;
END $$;
